name: recliq_user
description: A digital recycling app for users to earn money from recyclables.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  provider: ^6.0.5
  
  # Routing
  go_router: ^10.1.0
  
  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.3.0
  
  # Storage
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  
  # UI Components
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  
  # Utils
  intl: ^0.20.2
  logger: ^2.0.1
  dio: ^5.3.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
